name: Warps
version: ${project.version}
main: me.physicsarebad.warps.Warps
api-version: 1.13
authors: [ PhysicsAreBad ]
description: Demo warps plugin for Senior Team
commands:
  warps:
    aliases: [warp]
  addwarp:
permissions:
  warps.admin:
    default: op